### ISSUE TITLE
Always getting E_LOCK_NOT_OWNED for memory driver

### ISSUE THREAD

**Issue by ptasheq** [Julien-R44/verrou#12]
Hi Folks,

Thank you for all your hard work on this package. 

## Version

0.5.0

## Description

When I create lock inside controller (even for the simplest one) only the first use ends without an error. All subsequent requests cause exception with code `E_LOCK_NOT_OWNED`:

```
async handler({request, response}) {
	const lock_handle = locks.createLock('foobar', '1m');

	await lock_handle.run(async() => {
		await new Promise((resolve) => {
			setTimeout(() => {
				resolve(true);
			}, 100);
		});
	});

	return response.status(200).send([]);
}
```

Maybe I'm missing something obvious or I misunderstand the purpose of this package, but as I looked into [implementation](https://github.com/Julien-R44/verrou/blob/main/packages/verrou/src/drivers/memory.ts) I think that cleaning/updating the `owner` is missing here (subsequent `acquire`s do not update it, so it always has the value from the first request, so the non-equal condition is always true and we get an exception).

**Comment by Julien-R44** [comment]
indeed a problem linked to the cleaning logic, and you were totally right

Thank you for pointing out the problem. It will be available with the next version
