### ISSUE TITLE
"Cannot find module '@verrou/core' or its corresponding type declarations" after installing

### ISSUE THREAD

**Issue by ivan-prats** [Julien-R44/verrou#6]
Hello! 

I just installed the package in my repo to try it out for a current use case of locking using Kysely adapter and I'm having issues using it. 

Sharing project and error information for as much context as possible:

## Documentation reference 
Following the official documentation for the [Kisely driver](https://verrou.dev/docs/drivers#kysely)

## Error
When importing from inside my project:
```ts
import {LockFactory} from '@verrou/core';
import {kyselyStore} from '@verrou/core/drivers/kysely';
```
I get: `Cannot find module '@verrou/core' or its corresponding type declarations` & `Cannot find module '@verrou/core/drivers/kysely' or its corresponding type declarations`

## My project

At first I thought perhaps the package was not installed, but here is a screenshot of the downloaded package folder:
![image](https://github.com/Julien-R44/verrou/assets/63517766/25b79427-dd00-4bd0-9bc9-6c0cc879cd72)

Package installed: `"@verrou/core": "^0.5.0"`

Some of my package.json:
```json
{
  "name": "my-project",
  "version": "1.0.0",
  "main": "dist/index.js",
  "exports": {
    ".": "./dist/index.js"
  },
  "private": true,
  "dependencies": {
    "@verrou/core": "^0.5.0",
    "tslib": "^2.0.0",
    "typescript": "^5.2.2",
    ....
  },
  "devDependencies": {
    "ts-node-dev": "^2.0.0",
     ....
  }
}
```

`node -v `: v20.10.0

Perhaps there is something missing in the `exports` configuration of the package? Not sure tho.
Anything I can do or give you please say so and I will make my best 🙏

**Comment by Julien-R44** [comment]
Hey!
Verrou is ESM only. So you will need to have `type: "module"` in your package.json and also set `moduleResolution` to `NodeNext` or `Node16` in your tsconfig.json

**Comment by ivan-prats** [comment]
Oh wow I completely missed the warning in the quick setup section of the [docs](https://verrou.dev/docs/quick-setup)

Thanks for the quick response Julien! Closing the issue as it's something documented. As for us: I will try pressuring the team to move to changing the project module resolution & type, but it's going to be a hard sell. 

Keep up the great work!
