### ISSUE TITLE
Incorrect Implementation in Lock Factory Creation

### ISSUE THREAD

**Issue by AymaneAit** [Julien-R44/verrou#7]
Hello, thank you for providing this awesome package!

#### Problem
The current documentation for the `@verrou/core` package provides an incorrect implementation for creating a Lock Factory with Redis.

#### Current Implementation (as per documentation)
```ts
import { Verrou, LockFactory } from '@verrou/core'
import { redisStore } from '@verrou/core/drivers/redis'

const redis = new Redis({ ... })
const store = redisStore({ connection: redis })

const lockFactory = new LockFactory(store)
```

#### Correct implementation
```ts
import { Verrou, LockFactory } from '@verrou/core'
import { redisStore } from '@verrou/core/drivers/redis'

const redis = new Redis({ ... })
const store = redisStore({ connection: redis })

const lockFactory = new LockFactory(store.factory())
```

#### Explanation
In the correct implementation, we need to call the factory() method on the store object before passing it to the LockFactory constructor. 

#### Additional Information
I am currently using version **0.5.0**
Documentation link : [https://verrou.dev/docs/drivers](url)

Let me know if I am correct so I can submit a PR for this!

**Comment by Julien-R44** [comment]
Hey, thanks for the feedback!

The documentation is wrong. LockFactory is meant to be used like this :

```ts
import { LockFactory, Lock } from '@verrou/core'
import { RedisStore } from '@verrou/core/drivers/redis'
import { MemoryStore } from '@verrou/core/drivers/memory'

new LockFactory(new RedisStore({ connection: ioredis }))
new LockFactory(new MemoryStore())
```

Happy to accept a PR for documentation!

**Comment by Julien-R44** [comment]
Documentation updated
